/**
 * Complaint & Reward Categories
 */

export const COMPLAINT_CATEGORIES = {
  MAINTENANCE: 'MAINTENANCE',
  FOOD: 'FOOD',
  SECURITY: 'SECURITY',
  CLEANLINESS: 'CLEANLINESS',
  OTHER: 'OTHER',
} as const;

export const COMPLAINT_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export const REWARD_CATEGORIES = {
  CLEANLINESS: 'CLEANLINESS',
  PUNCTUALITY: 'PUNCTUALITY',
  BEHAVIOR: 'BEHAVIOR',
  PARTICIPATION: 'PARTICIPATION',
  PENALTY: 'PENALTY',
} as const;

export const NOTIFICATION_TYPES = {
  PAYMENT_DUE: 'PAYMENT_DUE',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  REWARD: 'REWARD',
  COMPLAINT_UPDATE: 'COMPLAINT_UPDATE',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM: 'SYSTEM',
} as const;
