export const COMPLAINT_CATEGORIES = {
  MAINTENANCE: 'MAINTENANCE',
  FOOD: 'FOOD',
  SECURITY: 'SECURITY',
  CLEANLINESS: 'CLEANLINESS',
  OTHER: 'OTHER',
} as const;

export const COMPLAINT_PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export const NOTIFICATION_TYPES = {
  PAYMENT_DUE: 'PAYMENT_DUE',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  COMPLAINT_UPDATE: 'COMPLAINT_UPDATE',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM: 'SYSTEM',
  CHALLAN_GENERATED: 'CHALLAN_GENERATED',
  CHALLAN_OVERDUE: 'CHALLAN_OVERDUE',
  CHALLAN_REMINDER: 'CHALLAN_REMINDER',
} as const;
